name: Main

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    env:
      CI: true
      DB_PORT: 33306

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        bundler-cache: true

    - name: Setup database
      run: |
        cp config/database.github-actions.yml config/database.yml
        cp config/server.yml.example config/server.yml

        sudo apt-get install -y mysql-client libmysqlclient-dev
        sudo /etc/init.d/mysql start

        RAILS_ENV=test bundle exec rake db:create

    - name: Run rubocop
      if: ${{ always() }}
      run: |
        bundle exec rubocop

    - name: Run cucumber
      if: ${{ always() }}
      run: |
        bundle exec cucumber --order random

    - name: Run rspec
      if: ${{ always() }}
      run: |
        bundle exec rspec spec --tag ~pending --order rand
